version: "3.5"

services:
    hub:
        image: selenium/hub:2.45.0
        container_name: delivery-selenium_hub
        ports:
            - "4444:4444"
        links:
            - delivery-web
        environment:
            - GRID_TIMEOUT=30000
            - GRID_BROWSER_TIMEOUT=30000
            - GRID_MAX_SESSION=20
            - GRID_TIMEOUT=12000
            - GRID_NEW_SESSION_WAIT_TIMEOUT=30000
            - GRID_DEBUG=true
            - GRID_CLEAN_UP_CYCLE=20000
            - SELENIUM_HUB_PARAMS=-enablePassThrough false
            - SELENIUM_NODE_PARAMS=-enablePassThrough false
    chrome:
        image: selenium/node-chrome-debug:2.45.0
        container_name: delivery-selenium_chrome
        stdin_open: true
        restart: always
        environment:
            HUB_HOST: delivery-selenium_hub
            NODE_MAX_INSTANCES: 10
            NODE_MAX_SESSION: 10
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
        links:
            - hub
    #     ports:
    #       - '5900:5900'
        depends_on:
            - hub
        networks:
            - rede_local
        shm_size: 128M
        volumes:
            - /dev/shm:/dev/shm
    firefox:
        image: selenium/node-firefox-debug:2.45.0
        container_name: delivery-selenium_firefox
        stdin_open: true
        restart: always
        environment:
            HUB_HOST: delivery-selenium_hub
            NODE_MAX_INSTANCES: 10
            NODE_MAX_SESSION: 10
            HUB_PORT_4444_TCP_ADDR: hub
            HUB_PORT_4444_TCP_PORT: 4444
        links:
            - hub
        ports:
            - '5900:5900'
        depends_on:
            - hub
        networks:
            - rede_local
        shm_size: 128M
        volumes:
            - /dev/shm:/dev/shm